version: '3.3'

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stationSki
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  app-spring:
    depends_on:
      - mysqldb
    image: gestion-ski:latest
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "root",
        "spring.jpa.hibernate.ddl-auto": "update"}'
    stdin_open: true
    tty: true

  app-angular:
   depends_on:
      - app-spring
    build: ./angular
    restart: on-failure
    ports:
      - "4200:4200"
    
volumes:
  db: