version: '3.3'

services:
  my-application:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/gestionski
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    volumes:
      - ./logs:/app/logs
    restart: always

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: gestionski
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
