version: '3.8'  # N'oubliez pas de définir la version ici

services:
  app:
    image: gestion-station-ski:1.0
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring": {
          "datasource": {
            "url": "jdbc:mysql://db:3306/stationSki?createDatabaseIfNotExist=true",  # Correction ici
            "username": "root",
            "password": "my-secret-pw"  
          },
          "jpa": {
            "properties": {
              "hibernate": {
                "dialect": "org.hibernate.dialect.MySQL5InnoDBDialect"
              }
            }
          }
        }
      }'
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "my-secret-pw"
      MYSQL_DATABASE: stationSki
    ports:
      - "3307:3306"  # Expose le port 3306 du conteneur sur le port 3307 de l'hôte
